### ISSUE TITLE
Add general links for Insights for AAP

### ISSUE THREAD

**Issue by mrjoshuap** [ansible/slides#2]
I'd love to add the links for Insights for AAP deck to this landing page!

https://docs.google.com/presentation/d/1G1yExRBdEUFAHPyN6wAJ8deK_obKU5ZKfhYgAqIf6tY/edit#slide=id.g10765a6bc6e_0_752

**Comment by IPvSean** [comment]
added, and John Spinks will update that deck post- RH Summit
