### ISSUE TITLE
Slide Deck Typos

### ISSUE THREAD

**Issue by mogreen1** [ansible/slides#38]
Slide Deck Name: ABU | ANA | 101 - Ansible network automation Network Automation Opportunity & Use Cases
Slide: 34
Slide Section: Why Red Hat
Issue: Two Typos

1. **_Red Hat to develop_** an ‘automation-first’ mindset, and as a result, automate many processes that have traditionally been manual and time-consuming.

2. They _**works**_ with Red Hat services to learn and implement agile, CI/CD and other processes as well as improve collaboration.

**Comment by IPvSean** [comment]
I have updated this slide, please reopen this if it is still confusing
