### ISSUE TITLE
Insights Slides

### ISSUE THREAD

**Issue by sarcilat** [ansible/slides#40]
The presentation of insights for Ansible are deprecated, I consider that maybe you can redirect to the new presentation, or to another one

**Comment by IPvSean** [comment]
taking a look

**Comment by IPvSean** [comment]
this is removed from devel: https://ipvsean.github.io/slides/

will be removed from main soon! thank you for opening the issue @sarcilat !  I really appreciate you taking the time to alert me about the deck change.
